
full_rebuild: true
name: Wakanda FullStack JavaScript Platform
author: Wakanda SAS
url: http://wakanda.io
version: 0.1
repository: https://github.com/Wakanda/wakanda.io
branch: gh-pages
encoding: utf-8
version: 1.3
encoding: utf-8
gems:
  - jekyll-seo-tag
sass:
  sass_dir: _scss_partials
defaults:
  -
    values:
      layout: "index"
  - scope:
      path: ""
      type: marketplace
    values:
      layout: marketplace
exclude: [
.git,
.gitignore,
README.md,
LICENSE
]
collections:
  marketplace:
    output: true
